import ThemeRegistry from '@/components/theme/theme-registry';
import './globals.css';
import '@fortawesome/fontawesome-svg-core/styles.css';
import { config } from '@fortawesome/fontawesome-svg-core';
import { Toaster } from 'react-hot-toast';
import {NextIntlClientProvider} from 'next-intl';
config.autoAddCss = false;

// see Metadata  documentation: https://nextjs.org/docs/app/building-your-application/optimizing/metadata
export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

/**
 * This is a layout that applies to all the pages, including the globals.css
 * @param children
 * @returns
 */
export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body>
                <ThemeRegistry options={{ key: 'mui', prepend: true }}>
                    <Toaster
                        position="top-center"
                        toastOptions={{
                            style: {
                                background: 'whiteSmoke',
                                textAlign: 'center',
                                zIndex: '99999999',
                            },
                            duration: 3000,
                        }}
                    />
                    <NextIntlClientProvider>
                        {children}
                    </NextIntlClientProvider>
                </ThemeRegistry>
            </body>
        </html>
    );
}
