import ThemeRegistry from '@/components/theme/theme-registry';
import { AuthProvider } from '@/lib/auth/auth-context';
import QueryProvider from '@/components/shared/QueryProvider/query-provider';
import CapacitorPluginsInit from '@/components/shared/CapacitorPluginsInit/capacitor-plugins-init';
import OfflineBanner from '@/components/shared/OfflineBanner/offline-banner';
import './globals.css';
import '@fortawesome/fontawesome-svg-core/styles.css';
import { config } from '@fortawesome/fontawesome-svg-core';
import { Toaster } from 'react-hot-toast';
config.autoAddCss = false;

// see Metadata  documentation: https://nextjs.org/docs/app/building-your-application/optimizing/metadata
export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

/**
 * This is a layout that applies to all the pages, including the globals.css
 * @param children
 * @returns
 */
export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <head>
                {/* Enable safe area insets for devices with notches/camera islands.
                    viewport-fit=cover allows the webview to extend into the safe areas,
                    which is required for env(safe-area-inset-*) CSS to work. */}
                <meta name="viewport" content="width=device-width, initial-scale=1.0, viewport-fit=cover" />
                {/* Register service worker for SPA routing fallback in Capacitor.
                    Intercepts requests for dynamic routes (e.g., /spaces/75) and
                    serves the catch-all page when the static file doesn't exist. */}
                <script
                    dangerouslySetInnerHTML={{
                        __html: `
                            if ('serviceWorker' in navigator) {
                                navigator.serviceWorker.register('/capacitor-sw.js').catch(function() {});
                            }
                        `,
                    }}
                />
            </head>
            <body>
                <CapacitorPluginsInit />
                <ThemeRegistry options={{ key: 'mui', prepend: true }}>
                    <OfflineBanner />
                    <AuthProvider>
                        <QueryProvider>
                            <Toaster
                                position="top-center"
                                toastOptions={{
                                    style: {
                                        background: 'whiteSmoke',
                                        textAlign: 'center',
                                        zIndex: '99999999',
                                    },
                                    duration: 3000,
                                }}
                            />
                            {children}
                        </QueryProvider>
                    </AuthProvider>
                </ThemeRegistry>
            </body>
        </html>
    );
}
